// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// call_alleles_engine
Rcpp::List call_alleles_engine(Rcpp::DataFrame d, int top_n);
RcppExport SEXP _snpbeadchip_call_alleles_engine(SEXP dSEXP, SEXP top_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type top_n(top_nSEXP);
    rcpp_result_gen = Rcpp::wrap(call_alleles_engine(d, top_n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_snpbeadchip_call_alleles_engine", (DL_FUNC) &_snpbeadchip_call_alleles_engine, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_snpbeadchip(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
