# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

channel_probe_to_alleles_engine <- function(d, top_n) {
    .Call(`_snpbeadchip_channel_probe_to_alleles_engine`, d, top_n)
}

