# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

call_alleles_engine <- function(d, top_n = 0L) {
    .Call('_snpbeadchip_call_alleles_engine', PACKAGE = 'snpbeadchip', d, top_n)
}

