# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

to_plus_minus <- function(AB, SNP1, SNP2, illumina_strand, sep) {
    .Call(`_snpbeadchip_to_plus_minus`, AB, SNP1, SNP2, illumina_strand, sep)
}

call_alleles_ab_compare_engine <- function(d_lst, cutoff = 3, nc_int_thres = -1L, nc_snr_thres = -1.0, nc_sd_thres = -1.0, nc_nbeads_thres = -1L) {
    .Call(`_snpbeadchip_call_alleles_ab_compare_engine`, d_lst, cutoff, nc_int_thres, nc_snr_thres, nc_sd_thres, nc_nbeads_thres)
}

call_alleles_ab_engine <- function(d_lst, cutoff = 3, nc_int_thres = -1L, nc_snr_thres = -1.0, nc_sd_thres = -1.0, nc_nbeads_thres = -1L) {
    .Call(`_snpbeadchip_call_alleles_ab_engine`, d_lst, cutoff, nc_int_thres, nc_snr_thres, nc_sd_thres, nc_nbeads_thres)
}

channel_probe_to_alleles_engine <- function(d, top_n) {
    .Call(`_snpbeadchip_channel_probe_to_alleles_engine`, d, top_n)
}

